
cache:
  directories:
    - 'vendor'
    - '$HOME/.composer/cache'

matrix:
  fast_finish: true
  include:
    -
      sudo: required
      os: 'linux'
      dist: trusty
      language: 'php'
      php: '7.0'
      env:
        - COMPOSER_NO_INTERACTION=1 COMPOSER_DISABLE_XDEBUG_WARN=1
    -
      os: 'osx'
      language: 'generic'
      env:
        - _PHP=php70 COMPOSER_NO_INTERACTION=1 COMPOSER_DISABLE_XDEBUG_WARN=1

before_install:
  - 'src-dev/scripts/travis/before_install.sh'

install:
  - 'src-dev/scripts/travis/install.sh'

script:
  - './vendor/bin/robo lint'
  - './vendor/bin/robo test'
